# Reviewdog configuration file
# https://github.com/reviewdog/reviewdog

# Global configuration
reviewdog:
  # GitHub token for posting reviews
  github_token: ${{ secrets.GITHUB_TOKEN }}
  
  # Reporter type
  reporter: github-pr-review
  
  # Level of issues to report (info, warning, error)
  level: error
  
  # Filter mode (diff_context, nofilter, added)
  filter_mode: diff_context

# ESLint configuration
eslint:
  # ESLint flags
  flags: "--ext .js,.jsx,.ts,.tsx ."
  
  # Fail on error
  fail_on_error: false
  
  # Reporter
  reporter: github-pr-review

# TypeScript configuration
typescript:
  # TypeScript flags
  flags: "--noEmit --pretty false"
  
  # Fail on error
  fail_on_error: false
  
  # Reporter
  reporter: github-pr-review

# Prettier configuration
prettier:
  # Prettier flags
  flags: "--check ."
  
  # Fail on error
  fail_on_error: false
  
  # Reporter
  reporter: github-pr-review 