module.exports = function (plop) {
  plop.setGenerator('component', {
    description: 'Cria um componente React com suporte a tema e i18n',
    prompts: [
      {
        type: 'input',
        name: 'name',
        message: 'Nome do componente',
      },
    ],
    actions: [
      {
        type: 'add',
        path: 'src/components/{{pascalCase name}}/{{pascalCase name}}.tsx',
        templateFile: 'plop-templates/component.tsx.hbs',
      },
      {
        type: 'add',
        path: 'src/components/{{pascalCase name}}/{{pascalCase name}}.test.tsx',
        templateFile: 'plop-templates/component.test.tsx.hbs',
      },
      {
        type: 'add',
        path: 'src/components/{{pascalCase name}}/{{pascalCase name}}.module.css',
        templateFile: 'plop-templates/component.module.css.hbs',
      },
      {
        type: 'add',
        path: 'src/locales/pt/{{camelCase name}}.json',
        template: `{
  "welcome": "Bem-vindo ao componente {{pascalCase name}}!",
  "description": "Este é um componente gerado pelo Plop."
}`,
      },
      {
        type: 'add',
        path: 'src/locales/en/{{camelCase name}}.json',
        template: `{
  "welcome": "Welcome to the {{pascalCase name}} component!",
  "description": "This is a component generated by Plop."
}`,
      },
    ],
  })

  plop.setGenerator('feature', {
    description:
      'Cria uma feature completa (API fake, store Zustand, componente Mantine, testes)',
    prompts: [
      {
        type: 'input',
        name: 'name',
        message: 'Nome da feature',
      },
    ],
    actions: [
      {
        type: 'add',
        path: 'src/features/{{camelCase name}}/api/{{camelCase name}}Api.ts',
        templateFile: 'plop-templates/feature/api.ts.hbs',
      },
      {
        type: 'add',
        path: 'src/features/{{camelCase name}}/store/use{{pascalCase name}}Store.ts',
        templateFile: 'plop-templates/feature/store.ts.hbs',
      },
      {
        type: 'add',
        path: 'src/features/{{camelCase name}}/components/{{pascalCase name}}.tsx',
        templateFile: 'plop-templates/feature/component.tsx.hbs',
      },
      {
        type: 'add',
        path: 'src/features/{{camelCase name}}/components/{{pascalCase name}}.test.tsx',
        templateFile: 'plop-templates/feature/component.test.tsx.hbs',
      },
      {
        type: 'add',
        path: 'src/features/{{camelCase name}}/components/{{pascalCase name}}.module.css',
        templateFile: 'plop-templates/feature/component.module.css.hbs',
      },
    ],
  })
}
