export { useArtistAlbums } from './useArtistAlbums'
export { useArtistDetails } from './useArtistDetails'
export { useArtistDetailsOptimized } from './useArtistDetailsOptimized'
export { useArtistPage } from './useArtistPage'
export { useArtistPrefetch } from './useArtistPrefetch'
export { useArtistTopTracks } from './useArtistTopTracks'
export { usePrefetch } from './usePrefetch'
export { useSpotifyAuth } from './useSpotifyAuth'
export { useSpotifySearch } from './useSpotifySearch'
export { useValidation } from './useValidation'

// New advanced features hooks
export { useAudioFeatures, useMultipleAudioFeatures } from './useAudioFeatures'
export { useAvailableGenres } from './useAvailableGenres'
export { useRecommendations } from './useRecommendations'
